#Global configurations
global:
  scrape_interval:     5s # Set the scrape interval to every 5 seconds.
  evaluation_interval: 5s # Evaluate rules every 5 seconds.

scrape_configs:
  - job_name: 'monitor-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['172.16.1.3:8080']

  - job_name: 'monitor-prm'
    static_configs:
      - targets: ['172.16.1.18:9090']

  - job_name: 'monitor-db'
    static_configs:
      - targets: ['172.16.1.2:3306']